# Generated by Django 3.2.7 on 2021-10-03 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_auto_20210918_2053'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoryproduct',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active'),
        ),
    ]
