# Generated by Django 3.2.7 on 2021-10-07 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_product_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoryproduct',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='active'),
        ),
    ]
